### ISSUE TITLE
该项目部署到私人服务器的方法 Requiring a method to deploy the project on VPS

### ISSUE THREAD

**Issue by hjsjhn** [TankNee/AnonymousQuestionBox#9]
README中主要描述的是如何在LeanCloud平台部署，而实际上也存在希望在VPS上部署运行的朋友，但是并不熟悉如何部署，如果该项目能够部署于VPS请问能否给出一个指南呢？

**Comment by TankNee** [comment]
完全可以部署在VPS上，因为示例就是这么做的，可以考虑写一个教程

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："hjsjhn ***@***.***&gt;;
发送时间：2023年2月28日(星期二) 晚上8:21
收件人："TankNee/AnonymousQuestionBox" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[TankNee/AnonymousQuestionBox] 该项目部署到私人服务器的方法 Requiring a method to deploy the project on VPS (Issue #9)
-----------------------------------

 

 
README中主要描述的是如何在LeanCloud平台部署，而实际上也存在希望在VPS上部署运行的朋友，但是并不熟悉如何部署，如果该项目能够部署于VPS请问能否给出一个指南呢？

**Comment by TankNee** [comment]
https://www.tanknee.cn/2023/03/03/17

可以参考这篇文章。
